enable_alert: true
ignore_tags: ["other_gpu", "others_gpu"]  # 増えるようだったらfnmatchで対応する
wandb_dir: /tmp/wandb
max_workers: 1

dashboard:
  entity: geniac-gpu
  project: gpu-dashboard4
  # project: gpu-dashboard2-dev  # for development
  tag_for_latest: latest

dataset:
  entity: geniac-gpu
  project: gpu-dashboard4
  artifact_name: all_runs_data

companies:
  ### Spectee — H100 x2（8/1–1/31）###
  - company: spectee-geniac
    teams: [spectee-geniac]
    schedule:
      - date: "2026-08-01"
        assigned_gpu_node: 2
      - date: "2027-02-01"
        assigned_gpu_node: 0

  ### ONESTRUCTION — H200 x10（7/31–1/31）###
  - company: onestruction-geniac
    teams: [onestruction-geniac]
    schedule:
      - date: "2026-07-31"
        assigned_gpu_node: 10
      - date: "2027-02-01"
        assigned_gpu_node: 0

  ### Asilla — H100 x4（7/20–1/20）###
  - company: asilla-geniac
    teams: [asilla-geniac]
    schedule:
      - date: "2026-07-20"
        assigned_gpu_node: 4
      - date: "2027-01-21"
        assigned_gpu_node: 0

  ### Preferred Networks — H200 x32（8/1–1/31）###
  - company: preferred-geniac
    teams: [preferred-geniac]
    schedule:
      - date: "2026-08-01"
        assigned_gpu_node: 32
      - date: "2027-02-01"
        assigned_gpu_node: 0

  ### Elith — H200（9/1–11/30 x2, 12/1–1/31 x1）###
  - company: elith-geniac
    teams: [elith-geniac]
    schedule:
      - date: "2026-09-01"
        assigned_gpu_node: 2
      - date: "2026-12-01"
        assigned_gpu_node: 1
      - date: "2027-02-01"
        assigned_gpu_node: 0

  ### biomy — H100/H200（非連続: 3段+空档補0）###
  - company: biomy-tech-geniac
    teams: [biomy-tech-geniac]
    schedule:
      - date: "2026-09-15"      # 9/15–9/18 H100 x2
        assigned_gpu_node: 2
      - date: "2026-09-19"      # 0
        assigned_gpu_node: 0
      - date: "2026-11-10"      # 11/10–12/10 H100 x5
        assigned_gpu_node: 5
      - date: "2026-12-11"      # 0
        assigned_gpu_node: 0
      - date: "2027-01-05"      # 1/5–5/7 H200 x9
        assigned_gpu_node: 9
      - date: "2027-05-08"
        assigned_gpu_node: 0

  ### Epigenetic AI — GB200（tray→node ÷2；7/1–6/30）###
  - company: epigeneticai-geniac
    teams: [epigeneticai-geniac]
    schedule:
      - date: "2026-07-01"
        assigned_gpu_node: 1      # 2 tray = 8 GPU
      - date: "2026-10-01"
        assigned_gpu_node: 25     # 50 tray = 200 GPU
      - date: "2027-01-01"
        assigned_gpu_node: 50     # 100 tray = 400 GPU
      - date: "2027-07-01"
        assigned_gpu_node: 0

  ### newmo — GB200 x9 Start Timing Pending ###
  - company: newmo-geniac
    teams:
      - newmo-geniac
    schedule:
      - date: "2026-07-01"
        assigned_gpu_node: 9
      - date: "2027-01-31"
        assigned_gpu_node: 0

  ### ABEJA — Timing and resource pending ###
  - company: abeja-geniac
    teams:
      - abeja-geniac
    schedule:
      - date: "2026-07-01"
        assigned_gpu_node: 0
      - date: "2027-01-31"
        assigned_gpu_node: 0