FROM --platform=linux/amd64 python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY config.yaml .
COPY src ./src

CMD ["python", "-m", "src.uploader.run_existence_checker"]